### ISSUE TITLE
2020?

### ISSUE THREAD

**Issue by sebastianovide** [LBreda/costituzione#3]
Sarebbe bello vedere il diff di quello che propongono in questo referendum del 2020

**Comment by LBreda** [comment]
Great minds think alike, volevo appunto fare un branch, probabilmente stasera lo trovi :)

**Comment by sebastianovide** [comment]
nel frattempo ho trovato i cambi... sono molto pochi: https://www.gazzettaufficiale.it/eli/id/2019/10/12/19A06354/sg
